-- 코드를 입력하세요
SELECT BOOK_ID, SUBSTR(TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD'),1,10) PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY='인문'
  AND EXTRACT(YEAR FROM PUBLISHED_DATE) = 2021
  ORDER BY PUBLISHED_DATE ASC